// PrivatePay demo runner.
//
// Runs the payroll lifecycle through the contract simulator and prints the
// public (ledger) transcript, showing what stays private vs what is disclosed.
//
//   node src/index.mjs
//
// For a real Midnight network, replace this with the driver generated by
// `compact compile` and connect the Lace wallet (see README "Talking to a
// real Midnight network").

import { initialState, actions, reduce } from "./ledger.js";

const log = (...args) => console.log(...args);

log("PrivatePay simulation (zero-dependency)");
log("-----------------------------------------");

let state = initialState();

const createPayroll = (totalAmount, payeeCount) => {
  state = reduce(state, { type: actions.CreatePayroll, amount: BigInt(totalAmount) });
  log(
    `createPayroll(total=${totalAmount}, payees=${payeeCount})  ` +
      `[payeeCount is configuration, total is disclosed]  ledger.total=${state}`
  );
};

const fund = (amount) => {
  state = reduce(state, { type: actions.Fund, amount: BigInt(amount) });
  log(`fund(amount=${amount})  [amount stays private]        ledger.total=${state}`);
};

const claim = (share, beneficiary) => {
  state = reduce(state, { type: actions.Claim, share: BigInt(share) });
  log(`claim(share=${share}, who=${beneficiary})  [share disclosed]  ledger.total=${state}`);
};

createPayroll(1000, 3);
fund(500);
claim(250, "alice");
claim(250, "bob");
claim(750, "carol");

log("");
log("Only the ledger.total column is public on-chain.");
log("Who funded what, and the originally-declared total breakdown, never leaves the circuit.");