// Ledger simulation for the PrivatePay contract.
//
// Mirrors the semantics of `contracts/private_pay.compact`: the on-chain state
// is a single Counter (`total`), and create/fund add to it while claim removes
// a disclosed share after asserting availability.
//
// A pure, dependency-free model so the whole repo installs and tests anywhere,
// including CI. The Typescript/jsdK contract driver generated by the real
// `compact compile` is the runner for live Midnight networks (see README).

export const initialState = () => 0n;

export const actions = {
  CreatePayroll: "CreatePayroll",
  Fund: "Fund",
  Claim: "Claim",
};

export function check(action, state) {
  switch (action.type) {
    case actions.CreatePayroll:
    case actions.Fund:
      return action.amount >= 0n;
    case actions.Claim:
      return action.share >= 0n && action.share <= state;
    default:
      return false;
  }
}

export function reduce(state, action) {
  switch (action.type) {
    case actions.CreatePayroll:
    case actions.Fund:
      return state + action.amount;
    case actions.Claim:
      if (!check(action, state)) {
        throw new Error("Claim rejected: share exceeds payroll balance");
      }
      return state - action.share;
    default:
      return state;
  }
}